name: CI/CD Workflow For Api Gateway

on:
  push:
    paths: 
      - Hospital-Management/api-gateway/**
      
jobs:
  pre-commit-scans:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Setup java
      uses: actions/setup-java@v4
      with:
         distribution: 'temurin' 
         java-version: '21'
        
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: GitLeaks Scan
      run: |
        docker pull devopsdynamo17/gitleaks
        docker run -v "$(pwd):/path" devopsdynamo17/gitleaks

    - name: Perform Google Formatter Check
      run: |
        cd Hospital-Management/api-gateway
        mvn com.spotify.fmt:fmt-maven-plugin:format

    - name: OSS scan
      run: |
        cd Hospital-Management/api-gateway
        mvn ossindex:audit
      continue-on-error: true

    - name: OWASP scan
      if: false 
      run: |
        cd Hospital-Management/api-gateway
        mvn org.owasp:dependency-check-maven:format

    - name: License finder
      run: |
        cd Hospital-Management/api-gateway
        docker pull devopsdynamo17/license-finder
        docker run -v "$(pwd):/scan" devopsdynamo17/license-finder
      continue-on-error: true
        
    - name: Build code and create docker images
      run: |
        cd Hospital-Management/api-gateway
        mvn clean install docker:build -Dimage.registry=${{vars.DOCKER_REGISTRY_USER}} -Dimage.tag=$GITHUB_REF_NAME
  
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{vars.DOCKER_REGISTRY_USER}}
        password: ${{secrets.DOCKER_REGISTRY_PAT}}


    - name: Push docker images
      run: |
        cd Hospital-Management/api-gateway
        CURRENT_FOLDER_NAME=$(basename $(pwd))
        docker push ${{vars.DOCKER_REGISTRY_USER}}/$CURRENT_FOLDER_NAME:$GITHUB_REF_NAME
