name: CI/CD Workflow For Directory-Service


on:
  push:
    paths:
      - Hospital-Management/directory-service/**
      
jobs:
  pre-commit-scans:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Setup java
      uses: actions/setup-java@v4
      with:
         distribution: 'temurin' 
         java-version: '21'
        
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: GitLeaks Scan
      run: |
        docker pull devopsdynamo17/gitleaks
        docker run -v "$(pwd):/path" devopsdynamo17/gitleaks

    - name: Perform Google Formatter Check
      run: |
        cd Hospital-Management/directory-service
        mvn com.spotify.fmt:fmt-maven-plugin:format

    - name: OSS scan
      run: |
        cd Hospital-Management/directory-service
        mvn ossindex:audit
      continue-on-error: true

    - name: OWASP scan
      if: false 
      run: |
        cd Hospital-Management/directory-service
        mvn org.owasp:dependency-check-maven:check

    - name: License finder
      run: |
        cd Hospital-Management/directory-service
        docker pull devopsdynamo17/license-finder
        docker run -v "$(pwd):/scan" devopsdynamo17/license-finder
      continue-on-error: true

    - name: Build code and create docker images
      run: |
        cd Hospital-Management/directory-service
        mvn install docker:build -Dimage.registry=${{vars.DOCKER_REGISTRY_USER}} -Dimage.tag=$GITHUB_REF_NAME
  
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{vars.DOCKER_REGISTRY_USER}}
        password: ${{secrets.DOCKER_REGISTRY_PAT}}

    - name: Push Docker images
      run: |
        cd Hospital-Management/directory-service
        CURRENT_FOLDER_NAME=$(basename $(pwd))
        docker push ${{vars.DOCKER_REGISTRY_USER}}/$CURRENT_FOLDER_NAME:$GITHUB_REF_NAME
